# =========================
# One Dark Colors
# =========================

# Foreground / Background
foreground            #abb2bf
background            #1e2127

# Selection
selection_foreground  #1e2127
selection_background  #3e4451

# Cursor
cursor                #61afef
cursor_text_color     #1e2127

# URL highlight
url_color             #56b6c2

# Window borders
active_border_color   #61afef
inactive_border_color #3e4451
bell_border_color     #e06c75

# Tab bar
active_tab_foreground   #1e2127
active_tab_background   #61afef
inactive_tab_foreground #abb2bf
inactive_tab_background #2c313c
tab_bar_background      #1e2127

# Marks
mark1_foreground #1e2127
mark1_background #56b6c2
mark2_foreground #1e2127
mark2_background #c678dd
mark3_foreground #1e2127
mark3_background #98c379

# 16 terminal colors
color0  #282c34
color8  #5c6370

color1  #e06c75
color9  #ff7b86

color2  #98c379
color10 #b6e3a1

color3  #e5c07b
color11 #ffd68a

color4  #61afef
color12 #7dcfff

color5  #c678dd
color13 #d795ff

color6  #56b6c2
color14 #7fdbca

color7  #abb2bf
color15 #ffffff
