# =========================
# Everforest Dark Colors
# =========================

# Foreground / Background
foreground            #d3c6aa
background            #2b3339

# Selection
selection_foreground  #2b3339
selection_background  #7fbbb3

# Cursor
cursor                #7fbbb3
cursor_text_color     #2b3339

# URL highlight
url_color             #83c092

# Window borders
active_border_color   #d699b6
inactive_border_color #4c555b
bell_border_color     #e67e80

# Tab bar
active_tab_foreground   #2b3339
active_tab_background   #d699b6
inactive_tab_foreground #d3c6aa
inactive_tab_background #3a454a
tab_bar_background      #2b3339

# Marks
mark1_foreground #2b3339
mark1_background #7fbbb3

mark2_foreground #2b3339
mark2_background #d699b6

mark3_foreground #2b3339
mark3_background #83c092

# =========================
# 16 terminal colors
# =========================

# black
color0  #3a454a
color8  #4c555b

# red
color1  #e67e80
color9  #f85552

# green
color2  #a7c080
color10 #b8d99f

# yellow
color3  #dbbc7f
color11 #e6c384

# blue
color4  #7fbbb3
color12 #9fd3c7

# magenta
color5  #d699b6
color13 #e0a9c5

# cyan
color6  #83c092
color14 #9fd9a5

# white
color7  #d3c6aa
color15 #fdf6e3
