$bg0 = rgb(282a36)
$bg1 = rgb(343746)

$fg0 = rgb(f8f8f2)
$fg1 = rgb(6272a4)

$accent = rgb(bd93f9)       # purple
$accent_alt = rgb(ff79c6)   # pink

$error = rgb(ff5555)
$warn = rgb(f1fa8c)
$info = rgb(8be9fd)
