$bg0 = rgb(232136)
$bg1 = rgb(2a273f)

$fg0 = rgb(e0def4)
$fg1 = rgb(908caa)

$accent = rgb(c4a7e7)      # iris (purple)
$accent_alt = rgb(9ccfd8)  # foam (cyan)

$error = rgb(eb6f92)
$warn = rgb(f6c177)
$info = rgb(31748f)
