# Extra autostart processes
exec-once = elephant
exec-once = walker --gapplication-service
exec-once = sleep 5 && waybar
exec-once = swayosd-server
exec-once = swww-daemon &
exec-once = sleep 1 && swww restore
exec-once = swaync
exec-once = hyprsunset
exec-once = hypridle
exec-once = hyprlock
exec-once = sleep 1 && hyprpm reload
exec-once = swayosd-client
exec-once = /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1


