# Application bindings
$terminal = kitty
$browser = brave

bind = SUPER, space, exec, ~/.config/rofi/launchers/type-2/launcher.sh || pkill rofi
#bind = SUPER, space, exec, walker
bind = SUPER, return, exec, $terminal
bind = SUPER, F, exec, nautilus --new-window
bind = SUPER, B, exec, $browser
bind = SUPERSHIFT, B, exec, brave --incognito
bind = SUPER, M, exec, spotify
bind = SUPER, T, togglefloating
bind = SUPER, E, exec, betterbird
bind = SUPER, W, killactive
bind = CONTROL, Print, exec, ~/.config/hypr/scripts/screenshot.sh
bind = , Print, exec, hyprshot -m output
bind = SHIFT, PRINT, exec, hyprshot -m region | satty --filename
bind = CONTROL_ALT, PRINT, exec, hyprshot -m window
bind = SUPER, R, exec, /home/igor/.config/waybar/scripts/waybar.sh
bind = SUPER, H, exec, /home/igor/.config/hypr/scripts/wall.sh
bind = SUPER, N, exec, ~/.config/hypr/scripts/relaunch.sh
bind = SUPER, L, exec, hyprlock
bind = CONTROL_ALT, DELETE, exec, /home/igor/.config/hypr/scripts/close-all.sh
# Windows move and resize
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow


# Windows focus

bind = SUPER, left, movefocus, l
bind = SUPER, down, movefocus, d
bind = SUPER, up, movefocus, u
bind = SUPER, right, movefocus, r


# Switch workspaces

bind = SUPER, 1, workspace, 1
bind = SUPER, 2, workspace, 2
bind = SUPER, 3, workspace, 3
bind = SUPER, 4, workspace, 4
bind = SUPER, 5, workspace, 5
bind = SUPER, 6, workspace, 6


# Move apps to workspaces

bind = SUPERSHIFT, 1, movetoworkspace, 1
bind = SUPERSHIFT, 2, movetoworkspace, 2
bind = SUPERSHIFT, 3, movetoworkspace, 3
bind = SUPERSHIFT, 4, movetoworkspace, 4
bind = SUPERSHIFT, 5, movetoworkspace, 5
bind = SUPERSHIFT, 6, movetoworkspace, 6


# Window resize keyboard

binde = SUPERSHIFT, right, resizeactive, 10 0
binde = SUPERSHIFT, left,  resizeactive, -10 0
