# See https://wiki.hyprland.org/Configuring/Window-Rules/ for more
#windowrule = suppressevent maximize, class:.*

# Just dash of opacity by default
windowrule = opacity 0.97 0.9, match:class ^(.*)$

# Fix some dragging issues with XWayland
windowrule {
  name = windowrule-1
  no_focus = on
  match:class = ^$
  match:title = ^$
  match:xwayland = 1
  match:float = 1
  match:fullscreen = 0
  match:pin = 0
}




# Blur Waybar
layerrule {
  name = waybar
  blur = on
  ignore_alpha = 0.5
  match:namespace = waybar
}


# Blur swaync
layerrule {
  name = swaync
  blur = on
  ignore_alpha = 0.5
  match:namespace = swaync-control-center
}

layerrule {
  name = layerrule-3
  blur = on
  ignore_alpha = 0.5
  match:namespace = swaync-notification-window
}




# Remove right-click menu blurring Chromium
windowrule {
  name = windowrule-2
  no_blur = on
  match:class = ^()$
  match:title = ^()
}



# Remove blur from Nautilus

windowrule {
  name = nautilus
  opacity = 1.0 override
  no_blur = off
  match:class = (org.gnome.Nautilus)
}



# Rofi

layerrule {
  name = rofi
  blur = on
  dim_around = on
  animation = popin 95%
  match:namespace = rofi
}



# Spotify

windowrule {
  name = spotify
  opacity = 1.0 override
  match:class = (spotify)
}


# Brave blur and transparency

windowrule {
  name = brave
  opacity = 1.0 override 1.0 override 1.0 override
  no_blur = off
  match:class = brave-browser
}




# Wlogout

layerrule {
  name = layerrule-5
  blur = on
  dim_around = on
  match:namespace = logout_dialog
}


# VSCodium

windowrule {
  name = windowrule-6
  opacity = 1.0 override
  match:class = (codium)
}

# Steam Workspace

windowrule = workspace 5, match:class ^(steam)$
windowrule = workspace 5, match:class ^(steamwebhelper)$

windowrule = workspace 5 silent, match:class ^(steam)$
windowrule = workspace 5 silent, match:class ^(steamwebhelper)$

# Spotify Workspace

windowrule = workspace 4, match:class ^(spotify)$
windowrule = workspace 4 silent, match:class ^(spotify)$


# Email Workspace

windowrule = workspace 6, match:class ^(eu.betterbird.Betterbird)$
windowrule = workspace 6 silent, match:class ^(eu.betterbird.Betterbird)$

# Browser Workspace

windowrule = workspace 3, match:class ^(brave-browser)$
windowrule = workspace 3 silent, match:class ^(brave-browser)$
