$bg0 = rgb(1a1b26)
$bg1 = rgb(24283b)

$fg0 = rgb(c0caf5)
$fg1 = rgb(a9b1d6)

$accent = rgb(7aa2f7)      # blue
$accent_alt = rgb(bb9af7)  # purple

$error = rgb(f7768e)
$warn = rgb(e0af68)
$info = rgb(73daca)
