# =========================
# Nightfox Colors
# =========================

# Foreground / Background
foreground            #cdcecf
background            #192330

# Selection
selection_foreground  #192330
selection_background  #3d4f63

# Cursor
cursor                #5fa3d7
cursor_text_color     #192330

# URL highlight
url_color             #63cdcf

# Window borders
active_border_color   #5fa3d7
inactive_border_color #3d4f63
bell_border_color     #c94f6d

# Tab bar
active_tab_foreground   #192330
active_tab_background   #5fa3d7
inactive_tab_foreground #cdcecf
inactive_tab_background #29394a
tab_bar_background      #192330

# Marks
mark1_foreground #192330
mark1_background #63cdcf
mark2_foreground #192330
mark2_background #c678dd
mark3_foreground #192330
mark3_background #81b29a

# 16 terminal colors
color0  #192330
color8  #4f6074

color1  #c94f6d
color9  #e06c75

color2  #81b29a
color10 #98c379

color3  #dbc074
color11 #e5c07b

color4  #5fa3d7
color12 #7dcfff

color5  #c678dd
color13 #d795ff

color6  #63cdcf
color14 #7fdbca

color7  #cdcecf
color15 #ffffff
