$bg0 = rgb(192330)
$bg1 = rgb(29394a)

$fg0 = rgb(cdcecf)
$fg1 = rgb(9aa5b1)

$accent = rgb(5fa3d7)      # blue
$accent_alt = rgb(c678dd)  # purple

$error = rgb(c94f6d)
$warn = rgb(d19a66)
$info = rgb(63cdcf)
