$bg0 = rgb(1c1e26)
$bg1 = rgb(232530)

$fg0 = rgb(c7c9cb)
$fg1 = rgb(9da0a2)

$accent = rgb(e95678)      # pink/red
$accent_alt = rgb(f09383)  # orange

$error = rgb(e95678)
$warn = rgb(fab795)
$info = rgb(59e1e3)
