$bg0 = rgb(1e2127)
$bg1 = rgb(2c313c)

$fg0 = rgb(abb2bf)
$fg1 = rgb(828997)

$accent = rgb(61afef)      # blue
$accent_alt = rgb(c678dd)  # purple

$error = rgb(e06c75)
$warn = rgb(e5c07b)
$info = rgb(56b6c2)
