# =========================
# Kanagawa Dark Colors
# =========================

# Foreground / Background
foreground            #dcd7ba
background            #1f1f28

# Selection
selection_foreground  #1f1f28
selection_background  #7e9cd8

# Cursor
cursor                #7e9cd8
cursor_text_color     #1f1f28

# URL highlight
url_color             #7fb4ca

# Window borders
active_border_color   #957fb8
inactive_border_color #54546d
bell_border_color     #c34043

# Tab bar
active_tab_foreground   #1f1f28
active_tab_background   #957fb8
inactive_tab_foreground #dcd7ba
inactive_tab_background #2a2a37
tab_bar_background      #1f1f28

# Marks
mark1_foreground #1f1f28
mark1_background #7e9cd8

mark2_foreground #1f1f28
mark2_background #957fb8

mark3_foreground #1f1f28
mark3_background #6a9589

# =========================
# 16 terminal colors
# =========================

# black
color0  #2a2a37
color8  #54546d

# red
color1  #c34043
color9  #e82424

# green
color2  #76946a
color10 #98bb6c

# yellow
color3  #c0a36e
color11 #e6c384

# blue
color4  #7e9cd8
color12 #9abdf5

# magenta
color5  #957fb8
color13 #b8a1e3

# cyan
color6  #6a9589
color14 #7fb4ca

# white
color7  #c8c093
color15 #dcd7ba
